### ISSUE TITLE
CakePHP-Queue-Plugin on Windows does'n works 

### ISSUE THREAD

**Issue by notRuslan** [webtechnick/CakePHP-Queue-Plugin#1]
Hi,
I can create job (add to queue) , but not process it : 

C:\wamp\www\ruseller\app>cake Queue.queue process
## Welcome to CakePHP v2.5.3 Console

App : app
## Path: C:\wamp\www\ruseller\app\

Processing Queue.
'uptime' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to retrieve load avearge from uptime.
#0 C:\wamp\www\ruseller\app\Plugin\Queue\Model\QueueTask.php(358): QueueUtil::cu

rrentCpu()
#1 C:\wamp\www\ruseller\app\Plugin\Queue\Model\QueueTask.php(432): QueueTask->ne

xt(1, true, true)
#2 C:\wamp\www\ruseller\app\Plugin\Queue\Model\QueueTask.php(479): QueueTask->ru

nList()
#3 C:\wamp\www\ruseller\app\Plugin\Queue\Lib\Queue.php(110): QueueTask->process(

)
#4 C:\wamp\www\ruseller\app\Plugin\Queue\Console\Command\QueueShell.php(219): Qu

eue::process()
#5 C:\wamp\www\cake\lib\Cake\Console\Shell.php(437): QueueShell->process()
#6 C:\wamp\www\cake\lib\Cake\Console\ShellDispatcher.php(209): Shell->runCommand

('process', Array)
#7 C:\wamp\www\cake\lib\Cake\Console\ShellDispatcher.php(66): ShellDispatcher->d

ispatch()
#8 C:\wamp\www\cake\lib\Cake\Console\cake.php(54): ShellDispatcher::run(Array)
#9 {main}

---

May be I'm wrong.

BTW, Good job.

**Comment by webtechnick** [comment]
You're right. uptime is used to figure out cpu process, which is a mac and unix operation. Doesn't work on Windows. I'll have to add a work-around for windows users, or if you've written one, please submit a pull request for review.

**Comment by Fyr** [comment]
1. You can put simple fix-code in /Lib/QueueUtil.php (Ln 133):
   public static function currentCpu() {
       $isWin = isset($_SERVER['HTTP_USER_AGENT']) && strpos($_SERVER['HTTP_USER_AGENT'], 'Windows') !== false;
       if ($isWin) {
           return 10;
       }
   ...
2. "Complete tool to background and schedule your time consuming tasks..."
   What a lies... It's NOT working on background!!!
   I see 'Done!!!' only after shell work is complete. Expected: IMMEDIATELY!!!
   Please, do not mislead people

class TestQueueController extends AdminController {
    public $layout = false;

```
public function test() {
    $this->autoRender = false;
    App::uses('Queue', 'Queue.Lib');
    $task = Queue::add("hello", 'shell');
    echo '<pre>';
    print_r($task);
    $result = Queue::process();
    echo '<pre><br/>';
    $this->redirect(array('action' => 'test2'));
}

function test2() {
    $this->autoRender = false;
    echo 'Done!!!';
}
```

}

**Comment by notRuslan** [comment]
Fyr,
I disagree with you, I'm using that plugin about two years as for web interface and for CLI too.
Thanks to author.
And I made small modification for my needs.
May be you don't know how to use CLI for Cake scripts ? Ask here.

**Comment by Fyr** [comment]
I need to run background process that can take too much time. I want to track its progress while other tasks are run too. 
For ex. processing while DB can take too much time. I want to run the bkg task, then redirect a user to a progress page and by AJAX show him a progress.
How I can do it?

**Comment by Fyr** [comment]
And one more nuance. Bkg script should not be stopped by timeout or lost connection.

**Comment by notRuslan** [comment]
I think it's not related with Queue plugin.
I don't know nothing about your process , but you can release it by different ways.
As Example, if you have to UPDATE DB table with 10000 records, you can do it by 1000 rec. in on time - 
you can show progress increasing by 10% after each iteration.

**Comment by Fyr** [comment]
it's not a solution. however I need a solution to run some cake-code on bkg.

**Comment by prodigy7** [comment]
Fyr, maybe you should review the CakePHP-Queue-Plugin. It could be a part of a complete solution for bring some code into the background. But for that you should also understand how the plugin works, what it does and how it can take part in your solution.
If you need code running in the background, you must start it in a shell process and must build a suitable solution for your requirements how that background process can communicate with your foreground process. This plugin give you some usefull functions for that but you must finish your "project". There is no "full complete solution" in PHP.

**Comment by Fyr** [comment]
Question remains the same - how to run cakePHP-code on bkg?
If I run this plugin with cake-shell - it waits until shell is complete. Thus it's not a bkg process

**Comment by prodigy7** [comment]
Maybe you think something too narrow!

Now, it's easy: You need a script which process tasks given. Start point is your request, end point the function process your task. Between and around it is this plugin which takes your request, put it in the queue and get it if requested.
Now, the challenge is the end point. How is it triggered? A very simple and from my sight the easiest and best way is running every x minutes with a scheduler (cron in linux) a script which looks into the queue, what is todo and process that todo's.

On the on side this solution isn't maybe that way, your a looking for because the user in the frontend must wait for reaction. On the other side there isn't really a way bring frontend (your gui) and backend (background process) directly together. Windows native apps for example can do that because they run on one system and user action can handled directly, frontend and backend can be one (supported by threads).

Here we talk about php which runs on a server, generate some html, css and this is displayed in a browser. If the user reload the page or do any other things, you can't handle that directly (only with some others "workarounds"). You must design your application in that way, that frontend and backend can work independently.

Example: User do something on a page what result into a call which must be executed in the background. During this time if the user call that page again (leave side, come back again or reload the page) you must check a process is already running and if yes, you display a message, loader or something else. With ajax or simple reload you can check every x seconds or minutes run is done. If the background process has finished, you can display results and/or allow the user, trigger the action again.

Direct dependencys are hard to handle, so let each part run independendly and communicate over status which can for example stored to the database. Direct communication between frontend and backend are not possible. Other way could be, using threads (http://nl3.php.net/manual/en/class.thread.php). But I think, it's much more complex and not so solid like a queue solution.

Now, you should now find the answere how you can do that. If not, you should maybe invest some more in google ;-) Don't be angry, but here isn't really the right place explain the necessary basics and use cases. Some experience and knowledge is already necessary.
